export const BLOCKCHAIN_ADAPTER = 'BLOCKCHAIN_ADAPTER';
export const WALLET_ADAPTER = 'WALLET_ADAPTER';
export const EVENT_ADAPTER = 'EVENT_ADAPTER';
export const CONTRACT_ADAPTER = 'CONTRACT_ADAPTER';
export const AUTH_VERIFICATION_ADAPTER = 'AUTH_VERIFICATION_ADAPTER';
