/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrimaryMarketListing,
  IPrimaryMarketListingInterface,
} from "../../../../contracts/core/IssuerVault.sol/IPrimaryMarketListing";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "assetId",
        type: "bytes32",
      },
    ],
    name: "listings",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenAddress",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "assetId",
            type: "bytes32",
          },
          {
            internalType: "uint8",
            name: "listingType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "staticPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "reservePrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "clearingPrice",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "auctionPhase",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "sold",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "minInvestment",
            type: "uint256",
          },
        ],
        internalType: "struct IPrimaryMarketListing.Listing",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPrimaryMarketListing__factory {
  static readonly abi = _abi;
  static createInterface(): IPrimaryMarketListingInterface {
    return new Interface(_abi) as IPrimaryMarketListingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrimaryMarketListing {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPrimaryMarketListing;
  }
}
