/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYieldVaultSettlement,
  IYieldVaultSettlementInterface,
} from "../../../../contracts/core/IssuerVault.sol/IYieldVaultSettlement";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalSettlement",
        type: "uint256",
      },
    ],
    name: "depositSettlement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IYieldVaultSettlement__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldVaultSettlementInterface {
    return new Interface(_abi) as IYieldVaultSettlementInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IYieldVaultSettlement {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IYieldVaultSettlement;
  }
}
