import { ContractName } from '@openassets/types';

export const StellarContracts: Partial<Record<ContractName, string>> = {
  AttestationRegistry: 'CB5E5E3UIRIHAJLDPANTM64DYRE73J6BF7HTPS6JMF5AD6YWXZIVNPKR',
  TrustedIssuersRegistry: 'CCVP62PCN4KVFEIGGNWLPQ6DZGONWCU4KRZ22ED72WXFCEMKETTXM7RQ',
  IdentityRegistry: 'CAUQPRMDO4Y66EH6LRPT77MWUMITJOPSYBJR3IQVZCP4J4UZTZLGBSTK',
  AssetRegistry: 'CATAQATTDYNJEQ4VOLURXZA3J7X4AMNE3HTUUZJ5FGCOY2KCW5JFHEWA',
  PrimaryMarket: 'CB4VSKYAMBQFO4VFOND6MWSXMHQWBTG5PXNS7ZWYGIU7PWQM7X2ZBTZQ',
  YieldVault: 'CCSIHKPQTH3FMG5CIDGEAMIS6QBLHQBVINA7T2ZGAQOVZ32MO3Y7BL2S'
} as const;
