export enum NotificationAction {
  VIEW_ASSET = 'VIEW_ASSET',
  VIEW_PORTFOLIO = 'VIEW_PORTFOLIO',
  CLAIM_YIELD = 'CLAIM_YIELD',
  VIEW_MARKETPLACE = 'VIEW_MARKETPLACE',
  VIEW_KYC = 'VIEW_KYC',
  VIEW_TRUSTLINE_REQUESTS = 'VIEW_TRUSTLINE_REQUESTS',
  NONE = 'NONE',
}
