export enum NotificationType {
  ASSET_STATUS = 'ASSET_STATUS',
  KYC_STATUS = 'KYC_STATUS',
  YIELD_DISTRIBUTED = 'YIELD_DISTRIBUTED',
  PAYOUT_SETTLED = 'PAYOUT_SETTLED',
  TOKEN_PURCHASED = 'TOKEN_PURCHASED',
  TOKEN_DEPLOYED = 'TOKEN_DEPLOYED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  MARKETPLACE_LISTING = 'MARKETPLACE_LISTING',
  BID_PLACED = 'BID_PLACED',
  AUCTION_WON = 'AUCTION_WON',
  BID_REFUNDED = 'BID_REFUNDED',
  ORDER_FILLED = 'ORDER_FILLED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  ORDER_ACTIVE = 'ORDER_ACTIVE',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',

}

export enum NotificationSeverity {
  INFO = 'info',
  SUCCESS = 'success',
  WARNING = 'warning',
  ERROR = 'error',
}
