/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  USCCreditVerifier,
  USCCreditVerifierInterface,
} from "../../../contracts/integrations/USCCreditVerifier";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "sourceChain",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "eventType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "scoreDelta",
        type: "int256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "CrossChainEventVerified",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        internalType: "string",
        name: "sourceChain",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "eventType",
        type: "uint8",
      },
      {
        internalType: "int256",
        name: "scoreDelta",
        type: "int256",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "verifyAndRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461002857600080546001600160a01b031916331790556102fb908161002e8239f35b600080fdfe608060408181526004908136101561001657600080fd5b600092833560e01c9081638da5cb5b1461026a575063e8e9d1171461003a57600080fd5b346102665760a0366003190112610266576001600160a01b038235818116939192908490036102625760249267ffffffffffffffff92843584811161025e576100869036908301610292565b9590946044359360ff851680950361025a57608435828111610256576100af9036908601610292565b918b5416330361022357818b929183928951928392833781018381520390610fd25afa903d1561021b573d81811161020957865191601f8201601f19908116603f01168301908111838210176101f757875281523d8a602083013e5b816101ec575b816101bb575b50156101845750509183827fe56fef5a742468ce446398ed5f08135a77783dacb936f94dc0e402ee33fc31fd959460a0945195869460808652816080870152868601378383018501899052602084015260643590830152426060830152601f01601f19168101030190a280f35b906012606492602086519362461bcd60e51b8552840152820152711554d0ce881c1c9bdbd9881a5b9d985b1a5960721b6044820152fd5b80915051156101da57602001516001600160f81b031916151538610117565b50634e487b7160e01b88526032825287fd5b805115159150610111565b634e487b7160e01b8c5260418652848cfd5b634e487b7160e01b8b5260418552838bfd5b50606061010b565b865162461bcd60e51b8152602081870152600e818601526d2aa9a19d103737ba1037bbb732b960911b6044820152606490fd5b8a80fd5b8980fd5b8780fd5b8480fd5b8280fd5b84903461028e578160031936011261028e5790546001600160a01b03168152602090f35b5080fd5b9181601f840112156102c05782359167ffffffffffffffff83116102c057602083818601950101116102c057565b600080fdfea2646970667358221220c4c21056a03ef3916b2e23a18545a4bf9a001fad10ca6ed043bccff46c15ed8664736f6c63430008140033";

type USCCreditVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: USCCreditVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class USCCreditVerifier__factory extends ContractFactory {
  constructor(...args: USCCreditVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      USCCreditVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): USCCreditVerifier__factory {
    return super.connect(runner) as USCCreditVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): USCCreditVerifierInterface {
    return new Interface(_abi) as USCCreditVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): USCCreditVerifier {
    return new Contract(address, _abi, runner) as unknown as USCCreditVerifier;
  }
}
