/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as yieldVaultSol from "./YieldVault.sol";
export type { yieldVaultSol };
export type { AttestationRegistry } from "./AttestationRegistry";
export type { ComplianceModule } from "./ComplianceModule";
export type { IdentityRegistry } from "./IdentityRegistry";
export type { RWAToken } from "./RWAToken";
export type { TokenFactory } from "./TokenFactory";
export type { TrustedIssuersRegistry } from "./TrustedIssuersRegistry";
