/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TokenFactory {
  export type TokenSuiteStruct = {
    token: AddressLike;
    compliance: AddressLike;
    deployedAt: BigNumberish;
    totalSupply: BigNumberish;
  };

  export type TokenSuiteStructOutput = [
    token: string,
    compliance: string,
    deployedAt: bigint,
    totalSupply: bigint
  ] & {
    token: string;
    compliance: string;
    deployedAt: bigint;
    totalSupply: bigint;
  };
}

export interface TokenFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allTokens"
      | "attestationRegistry"
      | "deployTokenSuite"
      | "deployedTokens"
      | "getAllTokens"
      | "getTokenByAssetId"
      | "identityRegistry"
      | "owner"
      | "platformCustody"
      | "tokenCount"
      | "trustedIssuersRegistry"
      | "yieldVault"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TokenSuiteDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "allTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attestationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployTokenSuite",
    values: [BytesLike, BigNumberish, string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedTokens",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenByAssetId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformCustody",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trustedIssuersRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldVault",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "allTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployTokenSuite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenByAssetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformCustody",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "trustedIssuersRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yieldVault", data: BytesLike): Result;
}

export namespace TokenSuiteDeployedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    token: AddressLike,
    compliance: AddressLike,
    totalSupply: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    token: string,
    compliance: string,
    totalSupply: bigint
  ];
  export interface OutputObject {
    assetId: string;
    token: string;
    compliance: string;
    totalSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TokenFactory;
  waitForDeployment(): Promise<this>;

  interface: TokenFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  attestationRegistry: TypedContractMethod<[], [string], "view">;

  deployTokenSuite: TypedContractMethod<
    [
      assetId: BytesLike,
      totalSupply: BigNumberish,
      name: string,
      symbol: string,
      issuer: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  deployedTokens: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint] & {
        token: string;
        compliance: string;
        deployedAt: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;

  getAllTokens: TypedContractMethod<[], [string[]], "view">;

  getTokenByAssetId: TypedContractMethod<
    [assetId: BytesLike],
    [TokenFactory.TokenSuiteStructOutput],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformCustody: TypedContractMethod<[], [string], "view">;

  tokenCount: TypedContractMethod<[], [bigint], "view">;

  trustedIssuersRegistry: TypedContractMethod<[], [string], "view">;

  yieldVault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "attestationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployTokenSuite"
  ): TypedContractMethod<
    [
      assetId: BytesLike,
      totalSupply: BigNumberish,
      name: string,
      symbol: string,
      issuer: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedTokens"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint] & {
        token: string;
        compliance: string;
        deployedAt: bigint;
        totalSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTokenByAssetId"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [TokenFactory.TokenSuiteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformCustody"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trustedIssuersRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "yieldVault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "TokenSuiteDeployed"
  ): TypedContractEvent<
    TokenSuiteDeployedEvent.InputTuple,
    TokenSuiteDeployedEvent.OutputTuple,
    TokenSuiteDeployedEvent.OutputObject
  >;

  filters: {
    "TokenSuiteDeployed(bytes32,address,address,uint256)": TypedContractEvent<
      TokenSuiteDeployedEvent.InputTuple,
      TokenSuiteDeployedEvent.OutputTuple,
      TokenSuiteDeployedEvent.OutputObject
    >;
    TokenSuiteDeployed: TypedContractEvent<
      TokenSuiteDeployedEvent.InputTuple,
      TokenSuiteDeployedEvent.OutputTuple,
      TokenSuiteDeployedEvent.OutputObject
    >;
  };
}
