export enum AnnouncementType {
  AUCTION_SCHEDULED = 'AUCTION_SCHEDULED',
  AUCTION_LIVE = 'AUCTION_LIVE',
  AUCTION_FAILED = 'AUCTION_FAILED',
  AUCTION_ENDED = 'AUCTION_ENDED',
  AUCTION_RESULTS_DECLARED = 'AUCTION_RESULTS_DECLARED',
  ASSET_LISTED = 'ASSET_LISTED',
}

export enum AnnouncementStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}
