export enum SettlementStatus {
  PENDING_CONVERSION = 'PENDING_CONVERSION',
  READY_FOR_DISTRIBUTION = 'READY_FOR_DISTRIBUTION',
  DISTRIBUTING = 'DISTRIBUTING',
  DISTRIBUTED = 'DISTRIBUTED',
  FAILED = 'FAILED',
}

export enum YieldClaimStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
}
