/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CTCLeverageVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "INITIAL_LTV"
      | "LIQUIDATION_THRESHOLD"
      | "createPosition"
      | "ctc"
      | "ctcDexIntegration"
      | "getHealthFactor"
      | "harvestYield"
      | "nextPositionId"
      | "owner"
      | "positions"
      | "primaryMarket"
      | "renounceOwnership"
      | "seniorPool"
      | "setPrimaryMarket"
      | "setYieldVault"
      | "transferOwnership"
      | "usdc"
      | "yieldVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PositionCreated"
      | "YieldHarvested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_LTV",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPosition",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      string,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "ctc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ctcDexIntegration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthFactor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "harvestYield",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPositionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "primaryMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seniorPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPrimaryMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "yieldVault",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_LTV",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ctc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ctcDexIntegration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "harvestYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPositionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "primaryMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seniorPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPrimaryMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setYieldVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yieldVault", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionCreatedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    ctcCollateral: BigNumberish,
    usdcBorrowed: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    ctcCollateral: bigint,
    usdcBorrowed: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    ctcCollateral: bigint;
    usdcBorrowed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldHarvestedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    ctcSwapped: BigNumberish,
    usdcReceived: BigNumberish,
    interestPaid: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    ctcSwapped: bigint,
    usdcReceived: bigint,
    interestPaid: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    ctcSwapped: bigint;
    usdcReceived: bigint;
    interestPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CTCLeverageVault extends BaseContract {
  connect(runner?: ContractRunner | null): CTCLeverageVault;
  waitForDeployment(): Promise<this>;

  interface: CTCLeverageVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  INITIAL_LTV: TypedContractMethod<[], [bigint], "view">;

  LIQUIDATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  createPosition: TypedContractMethod<
    [
      user: AddressLike,
      ctcAmount: BigNumberish,
      usdcToBorrow: BigNumberish,
      rwaToken: AddressLike,
      rwaTokenAmount: BigNumberish,
      assetId: string,
      assetIdBytes: BytesLike,
      ctcPriceUSD: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  ctc: TypedContractMethod<[], [string], "view">;

  ctcDexIntegration: TypedContractMethod<[], [string], "view">;

  getHealthFactor: TypedContractMethod<
    [positionId: BigNumberish, ctcPriceUSD: BigNumberish],
    [bigint],
    "view"
  >;

  harvestYield: TypedContractMethod<
    [positionId: BigNumberish, ctcPriceUSD: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        ctcSwapped: bigint;
        usdcReceived: bigint;
        interestPaid: bigint;
      }
    ],
    "nonpayable"
  >;

  nextPositionId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        user: string;
        ctcCollateral: bigint;
        usdcBorrowed: bigint;
        rwaToken: string;
        rwaTokenAmount: bigint;
        assetId: string;
        createdAt: bigint;
        lastHarvestTime: bigint;
        totalInterestPaid: bigint;
        liquidatedAt: bigint;
        active: boolean;
        inLiquidation: boolean;
      }
    ],
    "view"
  >;

  primaryMarket: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seniorPool: TypedContractMethod<[], [string], "view">;

  setPrimaryMarket: TypedContractMethod<
    [_primaryMarket: AddressLike],
    [void],
    "nonpayable"
  >;

  setYieldVault: TypedContractMethod<
    [_yieldVault: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  yieldVault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_LTV"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPosition"
  ): TypedContractMethod<
    [
      user: AddressLike,
      ctcAmount: BigNumberish,
      usdcToBorrow: BigNumberish,
      rwaToken: AddressLike,
      rwaTokenAmount: BigNumberish,
      assetId: string,
      assetIdBytes: BytesLike,
      ctcPriceUSD: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ctc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ctcDexIntegration"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHealthFactor"
  ): TypedContractMethod<
    [positionId: BigNumberish, ctcPriceUSD: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "harvestYield"
  ): TypedContractMethod<
    [positionId: BigNumberish, ctcPriceUSD: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        ctcSwapped: bigint;
        usdcReceived: bigint;
        interestPaid: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPositionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        user: string;
        ctcCollateral: bigint;
        usdcBorrowed: bigint;
        rwaToken: string;
        rwaTokenAmount: bigint;
        assetId: string;
        createdAt: bigint;
        lastHarvestTime: bigint;
        totalInterestPaid: bigint;
        liquidatedAt: bigint;
        active: boolean;
        inLiquidation: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "primaryMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seniorPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPrimaryMarket"
  ): TypedContractMethod<[_primaryMarket: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setYieldVault"
  ): TypedContractMethod<[_yieldVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "yieldVault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PositionCreated"
  ): TypedContractEvent<
    PositionCreatedEvent.InputTuple,
    PositionCreatedEvent.OutputTuple,
    PositionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "YieldHarvested"
  ): TypedContractEvent<
    YieldHarvestedEvent.InputTuple,
    YieldHarvestedEvent.OutputTuple,
    YieldHarvestedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PositionCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;
    PositionCreated: TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;

    "YieldHarvested(uint256,uint256,uint256,uint256)": TypedContractEvent<
      YieldHarvestedEvent.InputTuple,
      YieldHarvestedEvent.OutputTuple,
      YieldHarvestedEvent.OutputObject
    >;
    YieldHarvested: TypedContractEvent<
      YieldHarvestedEvent.InputTuple,
      YieldHarvestedEvent.OutputTuple,
      YieldHarvestedEvent.OutputObject
    >;
  };
}
