/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IPrimaryMarketListing {
  export type ListingStruct = {
    tokenAddress: AddressLike;
    assetId: BytesLike;
    listingType: BigNumberish;
    staticPrice: BigNumberish;
    minPrice: BigNumberish;
    reservePrice: BigNumberish;
    endTime: BigNumberish;
    clearingPrice: BigNumberish;
    auctionPhase: BigNumberish;
    totalSupply: BigNumberish;
    sold: BigNumberish;
    active: boolean;
    minInvestment: BigNumberish;
  };

  export type ListingStructOutput = [
    tokenAddress: string,
    assetId: string,
    listingType: bigint,
    staticPrice: bigint,
    minPrice: bigint,
    reservePrice: bigint,
    endTime: bigint,
    clearingPrice: bigint,
    auctionPhase: bigint,
    totalSupply: bigint,
    sold: bigint,
    active: boolean,
    minInvestment: bigint
  ] & {
    tokenAddress: string;
    assetId: string;
    listingType: bigint;
    staticPrice: bigint;
    minPrice: bigint;
    reservePrice: bigint;
    endTime: bigint;
    clearingPrice: bigint;
    auctionPhase: bigint;
    totalSupply: bigint;
    sold: bigint;
    active: boolean;
    minInvestment: bigint;
  };
}

export interface IPrimaryMarketListingInterface extends Interface {
  getFunction(nameOrSignature: "listings"): FunctionFragment;

  encodeFunctionData(functionFragment: "listings", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
}

export interface IPrimaryMarketListing extends BaseContract {
  connect(runner?: ContractRunner | null): IPrimaryMarketListing;
  waitForDeployment(): Promise<this>;

  interface: IPrimaryMarketListingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  listings: TypedContractMethod<
    [assetId: BytesLike],
    [IPrimaryMarketListing.ListingStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [IPrimaryMarketListing.ListingStructOutput],
    "view"
  >;

  filters: {};
}
