/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IssuerVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "SECONDS_PER_YEAR"
      | "USDC"
      | "authorizeMarket"
      | "authorizedMarkets"
      | "availableToWithdraw"
      | "calculateInterestOwed"
      | "getDebtSummary"
      | "owner"
      | "primaryMarket"
      | "recordDeposit"
      | "registerAsset"
      | "renounceOwnership"
      | "repayDebt"
      | "setYieldVault"
      | "transferOwnership"
      | "updateInterestRate"
      | "vaults"
      | "withdrawLiquidity"
      | "yieldVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetRegistered"
      | "DebtRepaid"
      | "DepositReceived"
      | "InterestRateUpdated"
      | "LiquidityWithdrawn"
      | "MarketAuthorized"
      | "OwnershipTransferred"
      | "VaultFullyRepaid"
      | "YieldDistributionTriggered"
      | "YieldVaultSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizeMarket",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedMarkets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "availableToWithdraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateInterestOwed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebtSummary",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "primaryMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordDeposit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayDebt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setYieldVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateInterestRate",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vaults", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "withdrawLiquidity",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldVault",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableToWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateInterestOwed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDebtSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "primaryMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setYieldVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yieldVault", data: BytesLike): Result;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    rwaToken: AddressLike,
    issuer: AddressLike,
    rateBps: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    rwaToken: string,
    issuer: string,
    rateBps: bigint
  ];
  export interface OutputObject {
    assetId: string;
    rwaToken: string;
    issuer: string;
    rateBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebtRepaidEvent {
  export type InputTuple = [
    assetId: BytesLike,
    principalRepaid: BigNumberish,
    interestRepaid: BigNumberish,
    remainingDebt: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    principalRepaid: bigint,
    interestRepaid: bigint,
    remainingDebt: bigint
  ];
  export interface OutputObject {
    assetId: string;
    principalRepaid: bigint;
    interestRepaid: bigint;
    remainingDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositReceivedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    amount: BigNumberish,
    totalHeld: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    amount: bigint,
    totalHeld: bigint
  ];
  export interface OutputObject {
    assetId: string;
    amount: bigint;
    totalHeld: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterestRateUpdatedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    oldRateBps: BigNumberish,
    newRateBps: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    oldRateBps: bigint,
    newRateBps: bigint
  ];
  export interface OutputObject {
    assetId: string;
    oldRateBps: bigint;
    newRateBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityWithdrawnEvent {
  export type InputTuple = [
    assetId: BytesLike,
    issuer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    issuer: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    assetId: string;
    issuer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketAuthorizedEvent {
  export type InputTuple = [market: AddressLike, authorized: boolean];
  export type OutputTuple = [market: string, authorized: boolean];
  export interface OutputObject {
    market: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultFullyRepaidEvent {
  export type InputTuple = [
    assetId: BytesLike,
    totalPrincipal: BigNumberish,
    totalInterest: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    totalPrincipal: bigint,
    totalInterest: bigint
  ];
  export interface OutputObject {
    assetId: string;
    totalPrincipal: bigint;
    totalInterest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDistributionTriggeredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    yieldVault: AddressLike,
    interestAmount: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    yieldVault: string,
    interestAmount: bigint
  ];
  export interface OutputObject {
    assetId: string;
    yieldVault: string;
    interestAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldVaultSetEvent {
  export type InputTuple = [yieldVault: AddressLike];
  export type OutputTuple = [yieldVault: string];
  export interface OutputObject {
    yieldVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IssuerVault extends BaseContract {
  connect(runner?: ContractRunner | null): IssuerVault;
  waitForDeployment(): Promise<this>;

  interface: IssuerVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_YEAR: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  authorizeMarket: TypedContractMethod<
    [market: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  authorizedMarkets: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  availableToWithdraw: TypedContractMethod<
    [assetId: BytesLike],
    [bigint],
    "view"
  >;

  calculateInterestOwed: TypedContractMethod<
    [assetId: BytesLike],
    [bigint],
    "view"
  >;

  getDebtSummary: TypedContractMethod<
    [assetId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        principalHeld: bigint;
        amountWithdrawn: bigint;
        outstandingDebt: bigint;
        interestOwed: bigint;
        totalOwed: bigint;
        agreedRateBps: bigint;
        withdrawalTimestamp: bigint;
        isFullyRepaid: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  primaryMarket: TypedContractMethod<[], [string], "view">;

  recordDeposit: TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAsset: TypedContractMethod<
    [
      assetId: BytesLike,
      rwaTokenAddress: AddressLike,
      issuerAddress: AddressLike,
      agreedRateBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayDebt: TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setYieldVault: TypedContractMethod<
    [_yieldVault: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateInterestRate: TypedContractMethod<
    [assetId: BytesLike, newRateBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  vaults: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        assetId: string;
        rwaTokenAddress: string;
        issuerAddress: string;
        principalHeld: bigint;
        amountWithdrawn: bigint;
        outstandingDebt: bigint;
        agreedRateBps: bigint;
        withdrawalTimestamp: bigint;
        totalInterestPaid: bigint;
        totalPrincipalRepaid: bigint;
        isRegistered: boolean;
        isFullyRepaid: boolean;
      }
    ],
    "view"
  >;

  withdrawLiquidity: TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldVault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeMarket"
  ): TypedContractMethod<
    [market: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedMarkets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "availableToWithdraw"
  ): TypedContractMethod<[assetId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateInterestOwed"
  ): TypedContractMethod<[assetId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDebtSummary"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        principalHeld: bigint;
        amountWithdrawn: bigint;
        outstandingDebt: bigint;
        interestOwed: bigint;
        totalOwed: bigint;
        agreedRateBps: bigint;
        withdrawalTimestamp: bigint;
        isFullyRepaid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "primaryMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDeposit"
  ): TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [
      assetId: BytesLike,
      rwaTokenAddress: AddressLike,
      issuerAddress: AddressLike,
      agreedRateBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayDebt"
  ): TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setYieldVault"
  ): TypedContractMethod<[_yieldVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateInterestRate"
  ): TypedContractMethod<
    [assetId: BytesLike, newRateBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        assetId: string;
        rwaTokenAddress: string;
        issuerAddress: string;
        principalHeld: bigint;
        amountWithdrawn: bigint;
        outstandingDebt: bigint;
        agreedRateBps: bigint;
        withdrawalTimestamp: bigint;
        totalInterestPaid: bigint;
        totalPrincipalRepaid: bigint;
        isRegistered: boolean;
        isFullyRepaid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "yieldVault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DebtRepaid"
  ): TypedContractEvent<
    DebtRepaidEvent.InputTuple,
    DebtRepaidEvent.OutputTuple,
    DebtRepaidEvent.OutputObject
  >;
  getEvent(
    key: "DepositReceived"
  ): TypedContractEvent<
    DepositReceivedEvent.InputTuple,
    DepositReceivedEvent.OutputTuple,
    DepositReceivedEvent.OutputObject
  >;
  getEvent(
    key: "InterestRateUpdated"
  ): TypedContractEvent<
    InterestRateUpdatedEvent.InputTuple,
    InterestRateUpdatedEvent.OutputTuple,
    InterestRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityWithdrawn"
  ): TypedContractEvent<
    LiquidityWithdrawnEvent.InputTuple,
    LiquidityWithdrawnEvent.OutputTuple,
    LiquidityWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MarketAuthorized"
  ): TypedContractEvent<
    MarketAuthorizedEvent.InputTuple,
    MarketAuthorizedEvent.OutputTuple,
    MarketAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VaultFullyRepaid"
  ): TypedContractEvent<
    VaultFullyRepaidEvent.InputTuple,
    VaultFullyRepaidEvent.OutputTuple,
    VaultFullyRepaidEvent.OutputObject
  >;
  getEvent(
    key: "YieldDistributionTriggered"
  ): TypedContractEvent<
    YieldDistributionTriggeredEvent.InputTuple,
    YieldDistributionTriggeredEvent.OutputTuple,
    YieldDistributionTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "YieldVaultSet"
  ): TypedContractEvent<
    YieldVaultSetEvent.InputTuple,
    YieldVaultSetEvent.OutputTuple,
    YieldVaultSetEvent.OutputObject
  >;

  filters: {
    "AssetRegistered(bytes32,address,address,uint256)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "DebtRepaid(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      DebtRepaidEvent.InputTuple,
      DebtRepaidEvent.OutputTuple,
      DebtRepaidEvent.OutputObject
    >;
    DebtRepaid: TypedContractEvent<
      DebtRepaidEvent.InputTuple,
      DebtRepaidEvent.OutputTuple,
      DebtRepaidEvent.OutputObject
    >;

    "DepositReceived(bytes32,uint256,uint256)": TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;
    DepositReceived: TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;

    "InterestRateUpdated(bytes32,uint256,uint256)": TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;
    InterestRateUpdated: TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;

    "LiquidityWithdrawn(bytes32,address,uint256,uint256)": TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;
    LiquidityWithdrawn: TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;

    "MarketAuthorized(address,bool)": TypedContractEvent<
      MarketAuthorizedEvent.InputTuple,
      MarketAuthorizedEvent.OutputTuple,
      MarketAuthorizedEvent.OutputObject
    >;
    MarketAuthorized: TypedContractEvent<
      MarketAuthorizedEvent.InputTuple,
      MarketAuthorizedEvent.OutputTuple,
      MarketAuthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VaultFullyRepaid(bytes32,uint256,uint256)": TypedContractEvent<
      VaultFullyRepaidEvent.InputTuple,
      VaultFullyRepaidEvent.OutputTuple,
      VaultFullyRepaidEvent.OutputObject
    >;
    VaultFullyRepaid: TypedContractEvent<
      VaultFullyRepaidEvent.InputTuple,
      VaultFullyRepaidEvent.OutputTuple,
      VaultFullyRepaidEvent.OutputObject
    >;

    "YieldDistributionTriggered(bytes32,address,uint256)": TypedContractEvent<
      YieldDistributionTriggeredEvent.InputTuple,
      YieldDistributionTriggeredEvent.OutputTuple,
      YieldDistributionTriggeredEvent.OutputObject
    >;
    YieldDistributionTriggered: TypedContractEvent<
      YieldDistributionTriggeredEvent.InputTuple,
      YieldDistributionTriggeredEvent.OutputTuple,
      YieldDistributionTriggeredEvent.OutputObject
    >;

    "YieldVaultSet(address)": TypedContractEvent<
      YieldVaultSetEvent.InputTuple,
      YieldVaultSetEvent.OutputTuple,
      YieldVaultSetEvent.OutputObject
    >;
    YieldVaultSet: TypedContractEvent<
      YieldVaultSetEvent.InputTuple,
      YieldVaultSetEvent.OutputTuple,
      YieldVaultSetEvent.OutputObject
    >;
  };
}
