/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ctcFaucetSol from "./CTCFaucet.sol";
export * as faucetSol from "./Faucet.sol";
export { MockCTC__factory } from "./MockCTC__factory";
export { MockCTCDEX__factory } from "./MockCTCDEX__factory";
export { MockUSDC__factory } from "./MockUSDC__factory";
