/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MockPartnerProtocol {
  export type LoanStruct = {
    user: AddressLike;
    amount: BigNumberish;
    disbursedAt: BigNumberish;
    repaidAt: BigNumberish;
    repaid: boolean;
  };

  export type LoanStructOutput = [
    user: string,
    amount: bigint,
    disbursedAt: bigint,
    repaidAt: bigint,
    repaid: boolean
  ] & {
    user: string;
    amount: bigint;
    disbursedAt: bigint;
    repaidAt: bigint;
    repaid: boolean;
  };
}

export interface MockPartnerProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getLoan"
      | "getUserLoanIds"
      | "loans"
      | "owner"
      | "recordLoan"
      | "repay"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LoanDisbursed" | "LoanRepaid"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getLoan", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getUserLoanIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordLoan",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "repay", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserLoanIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
}

export namespace LoanDisbursedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    loanId: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    loanId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    loanId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    loanId: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    loanId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    loanId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockPartnerProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): MockPartnerProtocol;
  waitForDeployment(): Promise<this>;

  interface: MockPartnerProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLoan: TypedContractMethod<
    [loanId: BytesLike],
    [MockPartnerProtocol.LoanStructOutput],
    "view"
  >;

  getUserLoanIds: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  loans: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        disbursedAt: bigint;
        repaidAt: bigint;
        repaid: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordLoan: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, loanId: BytesLike],
    [void],
    "nonpayable"
  >;

  repay: TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BytesLike],
    [MockPartnerProtocol.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserLoanIds"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        disbursedAt: bigint;
        repaidAt: bigint;
        repaid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordLoan"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, loanId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[loanId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "LoanDisbursed"
  ): TypedContractEvent<
    LoanDisbursedEvent.InputTuple,
    LoanDisbursedEvent.OutputTuple,
    LoanDisbursedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;

  filters: {
    "LoanDisbursed(address,uint256,bytes32,uint256)": TypedContractEvent<
      LoanDisbursedEvent.InputTuple,
      LoanDisbursedEvent.OutputTuple,
      LoanDisbursedEvent.OutputObject
    >;
    LoanDisbursed: TypedContractEvent<
      LoanDisbursedEvent.InputTuple,
      LoanDisbursedEvent.OutputTuple,
      LoanDisbursedEvent.OutputObject
    >;

    "LoanRepaid(address,uint256,bytes32,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
  };
}
