/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IOAIDInterface extends Interface {
  getFunction(
    nameOrSignature: "issueCreditLine" | "recordPayment" | "revokeCreditLine"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "issueCreditLine",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPayment",
    values: [BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCreditLine",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "issueCreditLine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCreditLine",
    data: BytesLike
  ): Result;
}

export interface IOAID extends BaseContract {
  connect(runner?: ContractRunner | null): IOAID;
  waitForDeployment(): Promise<this>;

  interface: IOAIDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  issueCreditLine: TypedContractMethod<
    [
      user: AddressLike,
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      valueUSD: BigNumberish,
      solvencyPositionId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  recordPayment: TypedContractMethod<
    [
      creditLineId: BigNumberish,
      amount: BigNumberish,
      onTime: boolean,
      daysLate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  revokeCreditLine: TypedContractMethod<
    [creditLineId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "issueCreditLine"
  ): TypedContractMethod<
    [
      user: AddressLike,
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      valueUSD: BigNumberish,
      solvencyPositionId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPayment"
  ): TypedContractMethod<
    [
      creditLineId: BigNumberish,
      amount: BigNumberish,
      onTime: boolean,
      daysLate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCreditLine"
  ): TypedContractMethod<
    [creditLineId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
