/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace SolvencyVault {
  export type PositionStruct = {
    user: AddressLike;
    collateralToken: AddressLike;
    collateralAmount: BigNumberish;
    usdcBorrowed: BigNumberish;
    tokenValueUSD: BigNumberish;
    createdAt: BigNumberish;
    active: boolean;
    tokenType: BigNumberish;
  };

  export type PositionStructOutput = [
    user: string,
    collateralToken: string,
    collateralAmount: bigint,
    usdcBorrowed: bigint,
    tokenValueUSD: bigint,
    createdAt: bigint,
    active: boolean,
    tokenType: bigint
  ] & {
    user: string;
    collateralToken: string;
    collateralAmount: bigint;
    usdcBorrowed: bigint;
    tokenValueUSD: bigint;
    createdAt: bigint;
    active: boolean;
    tokenType: bigint;
  };
}

export interface SolvencyVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "LIQUIDATION_THRESHOLD"
      | "PRIVATE_ASSET_LTV"
      | "RWA_LTV"
      | "borrowUSDC"
      | "depositCollateral"
      | "getHealthFactor"
      | "getMaxBorrow"
      | "getPosition"
      | "liquidatePosition"
      | "liquidationListings"
      | "nextPositionId"
      | "oaid"
      | "owner"
      | "positions"
      | "primaryMarket"
      | "processLiquidationSettlement"
      | "renounceOwnership"
      | "repayLoan"
      | "seniorPool"
      | "setOAID"
      | "setPrimaryMarket"
      | "transferOwnership"
      | "usdc"
      | "withdrawCollateral"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralWithdrawn"
      | "LoanRepaid"
      | "OAIDCreditIssued"
      | "OwnershipTransferred"
      | "PositionCreated"
      | "PositionLiquidated"
      | "USDCBorrowed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_ASSET_LTV",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RWA_LTV", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrowUSDC",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCollateral",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxBorrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatePosition",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationListings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPositionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oaid", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "primaryMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processLiquidationSettlement",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seniorPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOAID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrimaryMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateral",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_ASSET_LTV",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RWA_LTV", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrowUSDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidatePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPositionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oaid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "primaryMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processLiquidationSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "seniorPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOAID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPrimaryMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateral",
    data: BytesLike
  ): Result;
}

export namespace CollateralWithdrawnEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [positionId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    amount: BigNumberish,
    principal: BigNumberish,
    interest: BigNumberish,
    remainingDebt: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    amount: bigint,
    principal: bigint,
    interest: bigint,
    remainingDebt: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    amount: bigint;
    principal: bigint;
    interest: bigint;
    remainingDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OAIDCreditIssuedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    creditLineId: BigNumberish,
    creditLimit: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    creditLineId: bigint,
    creditLimit: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    creditLineId: bigint;
    creditLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionCreatedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    user: AddressLike,
    collateralToken: AddressLike,
    collateralAmount: BigNumberish,
    tokenValueUSD: BigNumberish,
    tokenType: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    user: string,
    collateralToken: string,
    collateralAmount: bigint,
    tokenValueUSD: bigint,
    tokenType: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    user: string;
    collateralToken: string;
    collateralAmount: bigint;
    tokenValueUSD: bigint;
    tokenType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionLiquidatedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    marketplaceAssetId: BytesLike,
    discountedPrice: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    marketplaceAssetId: string,
    discountedPrice: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    marketplaceAssetId: string;
    discountedPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace USDCBorrowedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    amount: BigNumberish,
    totalDebt: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    amount: bigint,
    totalDebt: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    amount: bigint;
    totalDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SolvencyVault extends BaseContract {
  connect(runner?: ContractRunner | null): SolvencyVault;
  waitForDeployment(): Promise<this>;

  interface: SolvencyVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  LIQUIDATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  PRIVATE_ASSET_LTV: TypedContractMethod<[], [bigint], "view">;

  RWA_LTV: TypedContractMethod<[], [bigint], "view">;

  borrowUSDC: TypedContractMethod<
    [positionId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositCollateral: TypedContractMethod<
    [
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      tokenValueUSD: BigNumberish,
      tokenType: BigNumberish,
      issueOAID: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getHealthFactor: TypedContractMethod<
    [positionId: BigNumberish],
    [bigint],
    "view"
  >;

  getMaxBorrow: TypedContractMethod<
    [positionId: BigNumberish],
    [bigint],
    "view"
  >;

  getPosition: TypedContractMethod<
    [positionId: BigNumberish],
    [SolvencyVault.PositionStructOutput],
    "view"
  >;

  liquidatePosition: TypedContractMethod<
    [positionId: BigNumberish, marketplaceAssetId: BytesLike],
    [void],
    "nonpayable"
  >;

  liquidationListings: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  nextPositionId: TypedContractMethod<[], [bigint], "view">;

  oaid: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        user: string;
        collateralToken: string;
        collateralAmount: bigint;
        usdcBorrowed: bigint;
        tokenValueUSD: bigint;
        createdAt: bigint;
        active: boolean;
        tokenType: bigint;
      }
    ],
    "view"
  >;

  primaryMarket: TypedContractMethod<[], [string], "view">;

  processLiquidationSettlement: TypedContractMethod<
    [positionId: BigNumberish, saleProceeds: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayLoan: TypedContractMethod<
    [positionId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  seniorPool: TypedContractMethod<[], [string], "view">;

  setOAID: TypedContractMethod<[_oaid: AddressLike], [void], "nonpayable">;

  setPrimaryMarket: TypedContractMethod<
    [_primaryMarket: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  withdrawCollateral: TypedContractMethod<
    [positionId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRIVATE_ASSET_LTV"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RWA_LTV"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrowUSDC"
  ): TypedContractMethod<
    [positionId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositCollateral"
  ): TypedContractMethod<
    [
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      tokenValueUSD: BigNumberish,
      tokenType: BigNumberish,
      issueOAID: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getHealthFactor"
  ): TypedContractMethod<[positionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMaxBorrow"
  ): TypedContractMethod<[positionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [SolvencyVault.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidatePosition"
  ): TypedContractMethod<
    [positionId: BigNumberish, marketplaceAssetId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidationListings"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "nextPositionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oaid"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        user: string;
        collateralToken: string;
        collateralAmount: bigint;
        usdcBorrowed: bigint;
        tokenValueUSD: bigint;
        createdAt: bigint;
        active: boolean;
        tokenType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "primaryMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processLiquidationSettlement"
  ): TypedContractMethod<
    [positionId: BigNumberish, saleProceeds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<
    [positionId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "seniorPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setOAID"
  ): TypedContractMethod<[_oaid: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrimaryMarket"
  ): TypedContractMethod<[_primaryMarket: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawCollateral"
  ): TypedContractMethod<
    [positionId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CollateralWithdrawn"
  ): TypedContractEvent<
    CollateralWithdrawnEvent.InputTuple,
    CollateralWithdrawnEvent.OutputTuple,
    CollateralWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "OAIDCreditIssued"
  ): TypedContractEvent<
    OAIDCreditIssuedEvent.InputTuple,
    OAIDCreditIssuedEvent.OutputTuple,
    OAIDCreditIssuedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PositionCreated"
  ): TypedContractEvent<
    PositionCreatedEvent.InputTuple,
    PositionCreatedEvent.OutputTuple,
    PositionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionLiquidated"
  ): TypedContractEvent<
    PositionLiquidatedEvent.InputTuple,
    PositionLiquidatedEvent.OutputTuple,
    PositionLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "USDCBorrowed"
  ): TypedContractEvent<
    USDCBorrowedEvent.InputTuple,
    USDCBorrowedEvent.OutputTuple,
    USDCBorrowedEvent.OutputObject
  >;

  filters: {
    "CollateralWithdrawn(uint256,address,uint256)": TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;
    CollateralWithdrawn: TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;

    "LoanRepaid(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "OAIDCreditIssued(uint256,uint256,uint256)": TypedContractEvent<
      OAIDCreditIssuedEvent.InputTuple,
      OAIDCreditIssuedEvent.OutputTuple,
      OAIDCreditIssuedEvent.OutputObject
    >;
    OAIDCreditIssued: TypedContractEvent<
      OAIDCreditIssuedEvent.InputTuple,
      OAIDCreditIssuedEvent.OutputTuple,
      OAIDCreditIssuedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PositionCreated(uint256,address,address,uint256,uint256,uint8)": TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;
    PositionCreated: TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;

    "PositionLiquidated(uint256,bytes32,uint256)": TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;
    PositionLiquidated: TypedContractEvent<
      PositionLiquidatedEvent.InputTuple,
      PositionLiquidatedEvent.OutputTuple,
      PositionLiquidatedEvent.OutputObject
    >;

    "USDCBorrowed(uint256,uint256,uint256)": TypedContractEvent<
      USDCBorrowedEvent.InputTuple,
      USDCBorrowedEvent.OutputTuple,
      USDCBorrowedEvent.OutputObject
    >;
    USDCBorrowed: TypedContractEvent<
      USDCBorrowedEvent.InputTuple,
      USDCBorrowedEvent.OutputTuple,
      USDCBorrowedEvent.OutputObject
    >;
  };
}
