/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBurnableToken,
  IBurnableTokenInterface,
} from "../../../../contracts/core/YieldVault.sol/IBurnableToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBurnableToken__factory {
  static readonly abi = _abi;
  static createInterface(): IBurnableTokenInterface {
    return new Interface(_abi) as IBurnableTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBurnableToken {
    return new Contract(address, _abi, runner) as unknown as IBurnableToken;
  }
}
