export const ASSET_ORIGINATION_SERVICE = 'ASSET_ORIGINATION_SERVICE';
export const MARKETPLACE_LISTING_SERVICE = 'MARKETPLACE_LISTING_SERVICE';
export const KYC_REGISTRATION_SERVICE = 'KYC_REGISTRATION_SERVICE';
export const TOKEN_DEPLOYMENT_SERVICE = 'TOKEN_DEPLOYMENT_SERVICE';
export const ADMIN_DOMAIN_STRATEGY = 'ADMIN_DOMAIN_STRATEGY';

export const MANTLE_ASSET_ORIGINATION_TOKEN = 'MANTLE_ASSET_ORIGINATION_TOKEN';
export const STELLAR_ASSET_ORIGINATION_TOKEN = 'STELLAR_ASSET_ORIGINATION_TOKEN';
export const CREDITCOIN_ASSET_ORIGINATION_TOKEN = 'CREDITCOIN_ASSET_ORIGINATION_TOKEN';

export const MANTLE_ADMIN_STRATEGY_TOKEN = 'MANTLE_ADMIN_STRATEGY_TOKEN';
export const STELLAR_ADMIN_STRATEGY_TOKEN = 'STELLAR_ADMIN_STRATEGY_TOKEN';
export const CREDITCOIN_ADMIN_STRATEGY_TOKEN = 'CREDITCOIN_ADMIN_STRATEGY_TOKEN';
