export const ASSET_ORIGINATION_SERVICE = 'ASSET_ORIGINATION_SERVICE';
export const MARKETPLACE_LISTING_SERVICE = 'MARKETPLACE_LISTING_SERVICE';
export const KYC_REGISTRATION_SERVICE = 'KYC_REGISTRATION_SERVICE';
export const TOKEN_DEPLOYMENT_SERVICE = 'TOKEN_DEPLOYMENT_SERVICE';
export const ADMIN_DOMAIN_STRATEGY = 'ADMIN_DOMAIN_STRATEGY';

export const MANTLE_ASSET_ORIGINATION_TOKEN = 'MANTLE_ASSET_ORIGINATION_TOKEN';
export const BNB_ASSET_ORIGINATION_TOKEN = 'BNB_ASSET_ORIGINATION_TOKEN';
export const STELLAR_ASSET_ORIGINATION_TOKEN = 'STELLAR_ASSET_ORIGINATION_TOKEN';
export const ARBITRUM_ASSET_ORIGINATION_TOKEN = 'ARBITRUM_ASSET_ORIGINATION_TOKEN';
export const CREDITCOIN_ASSET_ORIGINATION_TOKEN = 'CREDITCOIN_ASSET_ORIGINATION_TOKEN';

export const MANTLE_ADMIN_STRATEGY_TOKEN = 'MANTLE_ADMIN_STRATEGY_TOKEN';
export const HASHKEY_ADMIN_STRATEGY_TOKEN = 'HASHKEY_ADMIN_STRATEGY_TOKEN';
export const STELLAR_ADMIN_STRATEGY_TOKEN = 'STELLAR_ADMIN_STRATEGY_TOKEN';
export const ARBITRUM_ADMIN_STRATEGY_TOKEN = 'ARBITRUM_ADMIN_STRATEGY_TOKEN';
export const CREDITCOIN_ADMIN_STRATEGY_TOKEN = 'CREDITCOIN_ADMIN_STRATEGY_TOKEN';

import { NetworkType } from '@openassets/types';

export const NETWORK_TOKEN_MAP = {
    [NetworkType.MANTLE]: {
        [ASSET_ORIGINATION_SERVICE]: MANTLE_ASSET_ORIGINATION_TOKEN,
        [ADMIN_DOMAIN_STRATEGY]: MANTLE_ADMIN_STRATEGY_TOKEN,
    },
    [NetworkType.HASHKEY]: {
        [ASSET_ORIGINATION_SERVICE]: MANTLE_ASSET_ORIGINATION_TOKEN, // reuses EVM origination
        [ADMIN_DOMAIN_STRATEGY]: HASHKEY_ADMIN_STRATEGY_TOKEN,
    },
    [NetworkType.STELLAR]: {
        [ASSET_ORIGINATION_SERVICE]: STELLAR_ASSET_ORIGINATION_TOKEN,
        [ADMIN_DOMAIN_STRATEGY]: STELLAR_ADMIN_STRATEGY_TOKEN,
    },
    [NetworkType.ARBITRUM]: {
        [ASSET_ORIGINATION_SERVICE]: ARBITRUM_ASSET_ORIGINATION_TOKEN,
        [ADMIN_DOMAIN_STRATEGY]: ARBITRUM_ADMIN_STRATEGY_TOKEN,
    },
    [NetworkType.CREDITCOIN]: {
        [ASSET_ORIGINATION_SERVICE]: CREDITCOIN_ASSET_ORIGINATION_TOKEN,
        [ADMIN_DOMAIN_STRATEGY]: CREDITCOIN_ADMIN_STRATEGY_TOKEN,
    },
};
