/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TrustedIssuersRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTrustedIssuer"
      | "isTrustedIssuer"
      | "owner"
      | "removeTrustedIssuer"
      | "trustedIssuers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TrustedIssuerAdded" | "TrustedIssuerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTrustedIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeTrustedIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedIssuers",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addTrustedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeTrustedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedIssuers",
    data: BytesLike
  ): Result;
}

export namespace TrustedIssuerAddedEvent {
  export type InputTuple = [issuer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [issuer: string, timestamp: bigint];
  export interface OutputObject {
    issuer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedIssuerRemovedEvent {
  export type InputTuple = [issuer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [issuer: string, timestamp: bigint];
  export interface OutputObject {
    issuer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustedIssuersRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TrustedIssuersRegistry;
  waitForDeployment(): Promise<this>;

  interface: TrustedIssuersRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTrustedIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  isTrustedIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeTrustedIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedIssuers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTrustedIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isTrustedIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeTrustedIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "TrustedIssuerAdded"
  ): TypedContractEvent<
    TrustedIssuerAddedEvent.InputTuple,
    TrustedIssuerAddedEvent.OutputTuple,
    TrustedIssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedIssuerRemoved"
  ): TypedContractEvent<
    TrustedIssuerRemovedEvent.InputTuple,
    TrustedIssuerRemovedEvent.OutputTuple,
    TrustedIssuerRemovedEvent.OutputObject
  >;

  filters: {
    "TrustedIssuerAdded(address,uint256)": TypedContractEvent<
      TrustedIssuerAddedEvent.InputTuple,
      TrustedIssuerAddedEvent.OutputTuple,
      TrustedIssuerAddedEvent.OutputObject
    >;
    TrustedIssuerAdded: TypedContractEvent<
      TrustedIssuerAddedEvent.InputTuple,
      TrustedIssuerAddedEvent.OutputTuple,
      TrustedIssuerAddedEvent.OutputObject
    >;

    "TrustedIssuerRemoved(address,uint256)": TypedContractEvent<
      TrustedIssuerRemovedEvent.InputTuple,
      TrustedIssuerRemovedEvent.OutputTuple,
      TrustedIssuerRemovedEvent.OutputObject
    >;
    TrustedIssuerRemoved: TypedContractEvent<
      TrustedIssuerRemovedEvent.InputTuple,
      TrustedIssuerRemovedEvent.OutputTuple,
      TrustedIssuerRemovedEvent.OutputObject
    >;
  };
}
