/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBNBDEX,
  IBNBDEXInterface,
} from "../../../../contracts/integrations/BNBSwapIntegration.sol/IBNBDEX";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stARBAmount",
        type: "uint256",
      },
    ],
    name: "getQuote",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stARBAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minUSDCOut",
        type: "uint256",
      },
    ],
    name: "swapStARBForUSDC",
    outputs: [
      {
        internalType: "uint256",
        name: "usdcOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBNBDEX__factory {
  static readonly abi = _abi;
  static createInterface(): IBNBDEXInterface {
    return new Interface(_abi) as IBNBDEXInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBNBDEX {
    return new Contract(address, _abi, runner) as unknown as IBNBDEX;
  }
}
