/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IFluxionDEXInterface extends Interface {
  getFunction(
    nameOrSignature: "getQuote" | "swapMETHForUSDC"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapMETHForUSDC",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getQuote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapMETHForUSDC",
    data: BytesLike
  ): Result;
}

export interface IFluxionDEX extends BaseContract {
  connect(runner?: ContractRunner | null): IFluxionDEX;
  waitForDeployment(): Promise<this>;

  interface: IFluxionDEXInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getQuote: TypedContractMethod<[mETHAmount: BigNumberish], [bigint], "view">;

  swapMETHForUSDC: TypedContractMethod<
    [mETHAmount: BigNumberish, minUSDCOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getQuote"
  ): TypedContractMethod<[mETHAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapMETHForUSDC"
  ): TypedContractMethod<
    [mETHAmount: BigNumberish, minUSDCOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
