/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as primaryMarketSol from "./PrimaryMarket.sol";
export { SecondaryMarket__factory } from "./SecondaryMarket__factory";
