/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBNBSwapIntegration,
  IBNBSwapIntegrationInterface,
} from "../../../../contracts/core/BNBLeverageVault.sol/IBNBSwapIntegration";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stARBAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "stARBPriceUSD",
        type: "uint256",
      },
    ],
    name: "swapStARBToUSDC",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBNBSwapIntegration__factory {
  static readonly abi = _abi;
  static createInterface(): IBNBSwapIntegrationInterface {
    return new Interface(_abi) as IBNBSwapIntegrationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBNBSwapIntegration {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBNBSwapIntegration;
  }
}
